import { Providers } from "@/components/providers";
import { fontSans } from "@/config/fonts";
import { cn } from "@/helpers/auxiliary-helpers";
import "@/styles/globals.css";
import type { Metadata } from "next";
import type { ChildrenProps } from "@/types/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<ChildrenProps>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-[#fafafa] antialiased",
          fontSans.className,
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
